### ISSUE TITLE
Failed to remove 'C:\ProgramData\ASUS'. Reboot and try again error persists after reboot

### ISSUE THREAD

**Issue by SteveLockeUK** [codecrafting-io/asus-setup-tool#5]
I'm at a bit of a loss here. I suspect the issue is with whatever ASUS did when AC was installed.
If you do have any ideas for resolving this though it would be much appreciated.

![image](https://github.com/codecrafting-io/asus-setup-tool/assets/7005452/f7ac4605-b23c-4b94-826c-3cd74188ddbd)

**Comment by codecrafting-io** [comment]
Some process is blocking a file or folder in C:\ProgramData\Asus from being removed. You can try to run it again without a reboot, but a reboot is the most recommended way to fix.

**Comment by SteveLockeUK** [comment]
Rebooting didn't help. It seems as though something ASUS installed with AC was hanging on despite it's uninstall tool and your tool reporting it had been uninstalled.
I ended up using the windows reset function with the option to not remove files.

Appreciate your response here anyway as I'm confident the issue is with something ASUS' installer/AC had done rather than your tool!

**Comment by codecrafting-io** [comment]
@SteveLockeUK Are you using Armoury Crate with AuraSync?

**Comment by SteveLockeUK** [comment]
Yes, although one of the subdirectories referenced the ROG STRIX Scope 2 keyboard I'm using.
